apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      containers:
        - name: productpage
          image: docker.io/kanjava1911/productpage
          ports:
            - containerPort: 8080
          env:
            - name: MICRONAUT_SERVER_PORT
              value: "8080"
            - name: REVIEWS_URL
              value: "http://reviews:8080/reviews"
            - name: DETAILS_URL
              value: "http://details:8080/details"
          resources:
            requests:
              cpu: 100m
