apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      version: v1
  template:
    metadata:
      labels:
        app: postgres
        version: v1
    spec:
      containers:
        - name: postgres
          image: postgres:12.0-alpine
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              value: "root"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "test"
          volumeMounts:
            - name: postgres-initdb
              mountPath: /docker-entrypoint-initdb.d/initdb.sql
              subPath: initdb.sql
      volumes:
        - name: postgres-initdb
          configMap:
            name: postgres-initdb
