{
 "title": "kanjava1911",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "productpage cpu",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"^productpage-.*\"}[1m])",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "details cpu",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"^details-.*\"}[1m])",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "reviews cpu",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"^reviews-.*\"}[1m])",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "ratings cpu",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"^ratings-.*\"}[1m])",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "productpage memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"^productpage-.*\"} / (1024 * 1024)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "details memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"^details-.*\"} / (1024 * 1024)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "reviews memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"^reviews-.*\"} / (1024 * 1024)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "ratings memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"^ratings-.*\"} / (1024 * 1024)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}