version: "2"

services:
  db:
    image: postgres:12.0-alpine
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
