apiVersion: apps/v1
kind: Deployment
metadata:
  name: details
  labels:
    app: details
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
      version: v1
  template:
    metadata:
      labels:
        app: details
        version: v1
    spec:
      containers:
        - name: details
          image: docker.io/kanjava1911/details
          ports:
            - containerPort: 8080
          env:
            - name: MICRONAUT_SERVER_PORT
              value: "8080"
          resources:
            requests:
              cpu: 100m
